### PR TITLE
Switch feature and Avatar.js bug fix

### LINKED ISSUE #34: Create Switch component
https://material.io/guidelines/components/selection-controls.html#

### PR DESCRIPTION
**Pull request by jastra4**
https://docs-amnypfkmsw.now.sh/
fixes #34

### CODE REVIEW

File: src/components/Switch/Switch.js [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+
+class SwitchComponent extends PureComponent {
+  state = {
+    on: true,
+    off: false,
+  };
+
+  handleOnClick = () => {
+    if (!this.props.disabled) {
+      this.setState({
```
Comment (dekkofilms) [inline src/components/Switch/Switch.js]: Changing state functionally might be the better approach here since we are updating the component’s state using the current state. Using a function makes it more reliable, so for example:

```
this.setState(prevState => ({
    on: !prevState.on
    ...
}));
```

File: src/components/Switch/Switch.js [hunk 2]
```diff
@@ -0,0 +1,40 @@
+import React, { PureComponent } from 'react';
+import styled from 'styled-components';
+import SwitchTrack from './SwitchTrack';
+import SwitchThumb from './SwitchThumb';
+
+class SwitchComponent extends PureComponent {
+  state = {
+    on: true,
```
Comment (dekkofilms) [inline src/components/Switch/Switch.js]: Since off is always the opposite of on, we could just eliminate the need for even keeping track of off. We could just keep track of on.

**Comment by brad-decker** [comment]
Very nice work @jastra4

File: src/components/Switch/Switch.js (hunk 2 above)
Comment (jastra4) [reply src/components/Switch/Switch.js]: Thanks Taylor, I appreciate the feedback. I'll make sure to make those changes.

**Comment by martahj** [comment]
@dekkofilms Could you re-review this PR when you get a chance?
