### PR TITLE
fix(Dropdown): update styles

### LINKED ISSUE #179: Dropdown Menu (keyboard navigation)

### LINKED ISSUE #196: Dropdown request close
Clicking outside of open dropdown menu should close the menu component.

### LINKED ISSUE #197: Dropdown hover
The dropdown component should trigger a pointer cursor on hover

### LINKED ISSUE #199: Dropdown textdecoration
Dropdown textdecoration underline should match other textfields

https://material.io/guidelines/components/text-fields.html#text-fields-field-types

### PR DESCRIPTION
**Pull request by ashwoodall**
This PR

- fixes underline color to match theme styles
- adds pointer on hover
- adds request close when click is registered outside of an open menu
- allows dropdown menu to be tabbed into with keyboard

Resolve #199, Resolve #197, Resolve #196, Resolve #179 

Demo: https://docs-tcqmhzveck.now.sh/text-fields/

### CODE REVIEW

File: src/components/DropdownMenu.js [hunk 1]
```diff
@@ -74,7 +80,7 @@ export default class DropdownMenu extends Component {
   render() {
     const { options, isOpen, selected, isChrome } = this.state;
     return (
-      <div onClick={this.toggleSelect}>
+      <div onClick={this.toggleSelect} onFocus={() => this.setState({ isOpen: true })} tabIndex="0">
```
Comment (hsarb) [inline src/components/DropdownMenu.js]: could this be a handler thats bound to class? ```handleOpen```

File: src/components/DropdownMenu.js [hunk 2]
```diff
@@ -103,6 +109,7 @@ export default class DropdownMenu extends Component {
               aria-hidden="true"
               value={selected}
               open={isOpen}
+              onClose={() => this.handleClose()}
```
Comment (hsarb) [inline src/components/DropdownMenu.js]: I don't think this needs to be an arrow function: ```onClose={this.handleClose}```

File: src/components/DropdownMenu.js (hunk 1 above)
Comment (ashwoodall) [reply src/components/DropdownMenu.js]: I guess if you want to be smart about it 😎 Updated!
